### PR TITLE
added buttons to links

### PR DESCRIPTION
**Pull request by Jacqieq6464**
Discussed, reviewed and approved

### CODE REVIEW

**Review by Jacqieq6464 — COMMENTED** [review]
Reviewed & approved

**Review by Cgordon-bee — APPROVED** [review]

**Review by Jacqieq6464 — COMMENTED** [review]
Reviewed & approved

**Review by Jacqieq6464 — COMMENTED** [review]
Approved

**Review by Jacqieq6464 — COMMENTED** [review]
approved

**Review by Cgordon-bee — APPROVED** [review]

**Review by Cgordon-bee — APPROVED** [review]

**Pull request merged**
